### model
model_name_or_path: DongfuJiang/Qwen2.5-0.5B-Instruct

### method
stage: sft
do_train: true
finetuning_type: freeze
freeze_trainable_modules: all
freeze_extra_modules: aggregation_head,chunk_start_adapter_0,chunk_start_adapter_1,chunk_start_adapter_2,chunk_start_adapter_3,chunk_end_adapter_0,chunk_end_adapter_1,chunk_end_adapter_2,chunk_end_adapter_3

# deepspeed: examples/deepspeed/ds_z0_config.json
flash_attn: fa2

### dataset
dataset: qwen2.5_pro_magpie
dataset_dir: ../data
template: qwen
cutoff_len: 2048
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2_chunking_freeze_mlp
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

report_to: wandb
run_name: qwen2_chunking_freeze_mlp